### PR TITLE
Update gradle-wrapper version

### PR DESCRIPTION
**Pull request by josephworks**

### CODE REVIEW

**Comment by GMatrixGames** [comment]
You can't just update the properties, you need to run the gradle wrapper command to update it.

**Comment by josephworks** [comment]
what is that command?

**Comment by josephworks** [comment]
nvm i got it

**Comment by josephworks** [comment]
Its doing it

**Comment by josephworks** [comment]
@aolko 

```log
Updated to Gradle 5.6!

Here are the highlights of this release:
 - Incremental Groovy compilation
 - Groovy compile avoidance
 - Test fixtures for Java projects
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6/release-notes.html

```

**Comment by GMatrixGames** [comment]
Then why is it not committed to the repo, it should've changed the wrapper jar, gradlew file, and gradlew.bat file as well

**Comment by josephworks** [comment]
I will commit it after i fix some issues

**Comment by josephworks** [comment]
I cannot work on this until the regular kettle code finishes successfully.

**Pull request merged**
